apiVersion: v1
kind: ServiceAccount
metadata:
  name: assethub-api-server
  namespace: assethub
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: assethub-api-server
  namespace: assethub
rules:
  - apiGroups: ["assethub.project-catalyst.io"]
    resources: ["catalogversions"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: assethub-api-server
  namespace: assethub
subjects:
  - kind: ServiceAccount
    name: assethub-api-server
    namespace: assethub
roleRef:
  kind: Role
  name: assethub-api-server
  apiGroup: rbac.authorization.k8s.io
